version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "devparada"

    open-pull-requests-limit: 4
    versioning-strategy: "increase"  # Actualiza versiones a minor o patch en el package.json
    
    # Grupo 1: Solo dependencias de producción (dependencies)
    groups:
      production-dependencies:
        dependency-type: "production"
        commit-message:
          prefix: "pnpm"
          include: "scope"
          
      # Grupo 2: Solo dependencias de desarrollo (devDependencies)
      development-dependencies:
        dependency-type: "development"
        commit-message:
          prefix: "pnpm"
          include: "scope"
