version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "yarn"
      include: "scope" # Dependabot intentará usar (deps) o (deps-dev)
    assignees:
      - "devparada"

    open-pull-requests-limit: 4
    versioning-strategy: "increase"  # Actualiza versiones a minor o patch en el package.json
    
    # Grupo 1: Solo dependencias de producción (dependencies)
    groups:
      production-dependencies:
        dependency-type: "production"

      # Grupo 2: Solo dependencias de desarrollo (devDependencies)
      development-dependencies:
        dependency-type: "development"
