allowBuilds:
  esbuild: false
  sharp: false
overrides: # Descomentado para el futuro
  nanoid: 3.3.18
# Silencia las advertencias de peer dependencies para estas librerías sin alterar sus versiones
peerDependencyRules:
  allowAny:
    - "@emnapi/core"
    - "@emnapi/runtime"
minimumReleaseAge: 1440 # 24 horas
packages:
  - .
